// frontend/src/Leaderboard.jsx
import React, { useEffect, useState } from 'react'

const API_BASE = window.__API_BASE__ || 'http://localhost:8000'

export default function Leaderboard() {
  const [board, setBoard] = useState([])
  const [player, setPlayer] = useState('')
  const [score, setScore] = useState(0)

  async function load() {
    try {
      const res = await fetch(`${API_BASE}/leaderboard`)
      const j = await res.json()
      setBoard(j.board || [])
    } catch {}
  }

  async function submit() {
    try {
      await fetch(`${API_BASE}/leaderboard`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ player_id: player, score }) })
      load()
    } catch {}
  }

  useEffect(() => { load() }, [])

  return (
    <div style={{ marginTop: 12 }}>
      <h3>Leaderboard</h3>
      <ol>
        {board.map((e) => <li key={e.player_id + e.ts}>{e.player_id} — {Math.floor(e.score)}</li>)}
      </ol>
      <div>
        <input placeholder='player id' value={player} onChange={(e)=>setPlayer(e.target.value)} />
        <input type='number' placeholder='score' value={score} onChange={(e)=>setScore(Number(e.target.value))} style={{width:120,marginLeft:8}} />
        <button onClick={submit} style={{marginLeft:8}}>Submit</button>
      </div>
    </div>
  )
}

// admin/src/components/Leaderboard.vue
<template>
  <div style="padding-top:12px">
    <h3>Leaderboard</h3>
    <div v-if="loading">Loading…</div>
    <div v-else>
      <ol>
        <li v-for="entry in board" :key="entry.player_id + entry.ts">{{ entry.player_id }} — {{ Math.floor(entry.score) }}</li>
      </ol>
      <div style="margin-top:8px">
        <input v-model="playerId" placeholder="player id" />
        <input v-model.number="score" type="number" placeholder="score" style="width:120px;margin-left:8px" />
        <button @click="submit" style="margin-left:8px">Submit</button>
      </div>
      <div v-if="message" style="margin-top:8px">{{ message }}</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Leaderboard',
  data() {
    return { loading: true, board: [], playerId: '', score: 0, message: '' }
  },
  methods: {
    async load() {
      this.loading = true
      try {
        const base = window.__API_BASE__ || 'http://localhost:8000'
        const res = await fetch(`${base}/leaderboard`)
        const j = await res.json()
        this.board = j.board || []
      } catch (e) {
        this.message = 'Failed to load leaderboard.'
      } finally {
        this.loading = false
      }
    },
    async submit() {
      try {
        const base = window.__API_BASE__ || 'http://localhost:8000'
        const res = await fetch(`${base}/leaderboard`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ player_id: this.playerId, score: this.score }) })
        const j = await res.json()
        if (j.ok) {
          this.message = 'Submitted.'
          this.load()
        } else this.message = 'Submit failed.'
      } catch (e) {
        this.message = 'Submit failed.'
      }
    }
  },
  mounted() { this.load() }
}
</script>
